version: '2'

services:
    web:
        build: .
        env_file: .env
        ports:
        - '3333:3333'
        depends_on:
        - db

    db:
        image: postgres:9.6-alpine
        env_file: .env
        ports:
        - '35432:5432'

